* Fixed Bug GH:#341, Cubic can't extract files from original disk. Updated the extract-root command to ignore non-fatal exit status 2. * Fixed Bug GH:#282 "Close" button in the About dialog doesn't work. Reuse the on_close_about_dialog handler for the About dialog's response signal. * Fixed Bug GH:#340, Invalid escape sequence syntax warnings are displayed when installing or running Cubic. * Fixed Bug GH:#344, Gtk-WARNING Content added to the action area of a dialog using header bars. Added <property name="use-header-bar">0</property> to file choosers.

diff --git a/usr/share/cubic/commands/extract-root b/usr/share/cubic/commands/extract-root
--- a/usr/share/cubic/commands/extract-root
+++ b/usr/share/cubic/commands/extract-root
@@ -47,8 +47,9 @@ source_file_path=${2}
 # Command
 ########################################################################
 
+# Exit Status Codes
 # https://manpages.ubuntu.com/manpages/noble/man1/unsquashfs.1.html
-# EXIT STATUS
+#
 # 0 The filesystem listed or extracted OK.
 # 1 FATAL errors occurred, e.g. filesystem corruption, I/O errors.
 #   Unsquashfs did not continue and aborted.
@@ -58,5 +59,19 @@ source_file_path=${2}
 # See -ignore-errors, -strict-errors and -no-exit-code options for
 # how they affect the exit status.
 
-unsquashfs -force -no-exit-code -dest "${target_file_path}" "${source_file_path}"
+# Version 1:4.4 of unsquashfs, available in Ubuntu 20.04 LTS Focal Fossa, does
+# not support the "-no-exit-code" option.
+# unsquashfs -force -no-exit-code -dest "${target_file_path}" "${source_file_path}"
 
+unsquashfs -force -dest "${target_file_path}" "${source_file_path}"
+
+# Use echo $? to check the error status.
+# http://www.tldp.org/LDP/abs/html/exitcodes.html
+
+# Ignore non-fatal errors.
+exit_code=$?
+if [[ $exit_code -eq 2 ]]; then
+    echo "Ignoring non-fatal errors."
+    exit_code=0
+fi
+exit $exit_code
