* Fixed Bug GH:#403, Unable to extract Ubuntu Server 25.04 on Cubic 2025.06.90. The error "FATAL ERROR: create_inode: failed to create hardlink, because File exists" results when extracting Ubuntu 25.04 Server. Use the "-no-exit-code" and "-ignore-errors" options available in unsquashfs version 4.5+ (in Ubuntu 22.04+) to ignore errors while extracting the Linux file systems. Note, extract errors will not be ignored for unsquashfs 4.4 (in Ubuntu 21.10 and lower). * Changed the Cubic versioning scheme from YYYY.MM-RR to YYYY.MM.RR. (The dash "-" has been replaced by a dot "."). * Update the get_display_version() function in the constructor module to parse only the decimal portion of the package version.

diff --git a/usr/share/cubic/commands/extract-root b/usr/share/cubic/commands/extract-root
--- a/usr/share/cubic/commands/extract-root
+++ b/usr/share/cubic/commands/extract-root
@@ -37,18 +37,24 @@ program=${0}
 number_arguments=${#}
 target_file_path=${1}
 source_file_path=${2}
+has_error_option=${3}
 
 # echo "program..................... ${program}"
 # echo "number of arguments......... ${number_arguments}"
 # echo "target file path............ ${target_file_path}"
 # echo "source file path............ ${source_file_path}"
+# echo "has error option............ ${has_error_option}"
 
 ########################################################################
 # Command
 ########################################################################
 
 # Exit Status Codes
+#
+# https://manpages.ubuntu.com/manpages/focal/man1/unsquashfs.1.html
+# https://manpages.ubuntu.com/manpages/jammy/man1/unsquashfs.1.html
 # https://manpages.ubuntu.com/manpages/noble/man1/unsquashfs.1.html
+# https://manpages.ubuntu.com/manpages/plucky/man1/unsquashfs.1.html
 #
 # 0 The filesystem listed or extracted OK.
 # 1 FATAL errors occurred, e.g. filesystem corruption, I/O errors.
@@ -58,20 +64,63 @@ source_file_path=${2}
 #   output filesystem. Unsquashfs continued and did not abort.
 # See -ignore-errors, -strict-errors and -no-exit-code options for
 # how they affect the exit status.
-
-# Version 1:4.4 of unsquashfs, available in Ubuntu 20.04 LTS Focal Fossa, does
-# not support the "-no-exit-code" option.
-# unsquashfs -force -no-exit-code -dest "${target_file_path}" "${source_file_path}"
-
-unsquashfs -force -dest "${target_file_path}" "${source_file_path}"
-
+#
+# These options are available in squashfs version 4.5 and above.
+# -ignore-errors = treat errors writing files to output as non-fatal
+# -strict-errors = treat all errors as fatal
+# -no-exit-code = do not set exit code (to nonzero) on non-fatal errors
+#
+# The following versions of Ubuntu and squashfs do not support these options.
+#
+# Ubuntu Version                        Squashfs Version
+# ----------------------------------    ----------------
+# Ubuntu 20.04.6 LTS Focal Fossa        4.4
+# Ubuntu 20.10 Groovy Gorilla           4.4
+# Ubuntu 21.04 Hirsute Hippo            4.4
+# Ubuntu 21.10 Impish Indri             4.4
+#
+# The following versions of Ubuntu and squashfs support these options:
+#
+# Ubuntu Version                        Squashfs Version
+# ----------------------------------    ----------------
+# Ubuntu 22.04.5 LTS Jammy Jellyfish    4.5
+# Ubuntu 22.10 Kinetic Kudu             4.5.1
+# Ubuntu 23.04 Lunar Lobster            4.5.1
+# Ubuntu 23.10 Mantic Minotaur          4.6.1
+# Ubuntu 24.04.2 LTS Noble Numbat       4.6.1
+# Ubuntu 24.10 Oracular Oriole          4.6.1
+# Ubuntu 25.04 Plucky Puffin            4.6.1
+#
 # Use echo $? to check the error status.
 # http://www.tldp.org/LDP/abs/html/exitcodes.html
+#
+# The following fatal error occurs when extracting Ubuntu 25.04:
+# FATAL ERROR: create_inode: failed to create hardlink, because File exists
 
-# Ignore non-fatal errors.
-exit_code=$?
-if [[ $exit_code -eq 2 ]]; then
-    echo "Ignoring non-fatal errors."
-    exit_code=0
+if [[ ${has_error_option} ]]; then
+    # Ubuntu 22.04.5 LTS Jammy Jellyfish +
+    # Unsquashfs version 4.5+
+    unsquashfs -force -no-exit-code -ignore-errors -dest "${target_file_path}" "${source_file_path}"
+else
+    # Ubuntu 20.04 LTS Focal Fossa thru Ubuntu 21.10 Impish Indri
+    # Unsquashfs version 4.4
+    unsquashfs -force -dest "${target_file_path}" "${source_file_path}"
+    # # Use echo $? to check the error status.
+    # # http://www.tldp.org/LDP/abs/html/exitcodes.html
+    # exit_code=$?
+    # if [[ $exit_code -eq 1 ]]; then
+    #     # Ignore fatal errors.
+    #     # WARNING: The extract process may not have completed successfully due
+    #     # to the error.
+    #     echo "Ignoring fatal errors."
+    #     exit_code=0
+    # elif [[ $exit_code -eq 2 ]]; then
+    #     # Ignore non-fatal errors.
+    #     # WARNING: The extract process may not have completed successfully due
+    #     # to the error.
+    #     echo "Ignoring non-fatal errors."
+    #     exit_code=0
+    # fi
+    # exit $exit_code
 fi
-exit $exit_code
+
